# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "data/ref/starindex"
  # gtf file with transcripts
  annotation: "data/ref/iceplant_genome.gff_version_080819.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    week7-vs-control:
      - week7
      - control
    ongoing-vs-control:
      - ongoing
      - control

params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""

##
# Parameters for SRA data pull, populates samples.tsv and units.tsv
sradata:
  method: fasterq
  outdir: data/reads
  sra_list:
  -
    id: SRR000001
    label: sampleA
    condition: control
    unit: rep1
  -
    id: SRR000002
    label: sampleA
    condition: control
    unit: rep2
  -
    id: SRR000003
    label: sampleA
    condition: control
    unit: rep3
  -
    id: SRR000004
    label: sampleB
    condition: week7
    unit: rep1
  -
    id: SRR000005
    label: sampleB
    condition: week7
    unit: rep2
  -
    id: SRR000006
    label: sampleB
    condition: week7
    unit: rep3
  -
    id: SRR000007
    label: sampleC
    condition: ongoing
    unit: rep1
  -
    id: SRR000008
    label: sampleC
    condition: ongoing
    unit: rep2
  -
    id: SRR000009
    label: sampleC
    condition: ongoing
    unit: rep3
##
# Parameters for SRA data pull, populates samples.tsv and units.tsv
sradata:
  method: fasterq
  outdir: data/reads
  sra_list:
  -
    id: SRR000001
    label: sampleA
    condition: control
    unit: rep1
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000002
    label: sampleA
    condition: control
    unit: rep2
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000003
    label: sampleA
    condition: control
    unit: rep3
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000004
    label: sampleB
    condition: week7
    unit: rep1
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000005
    label: sampleB
    condition: week7
    unit: rep2
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000006
    label: sampleB
    condition: week7
    unit: rep3
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000007
    label: sampleC
    condition: ongoing
    unit: rep1
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000008
    label: sampleC
    condition: ongoing
    unit: rep2
    suffixes:
    - _1.fastq
    - _2.fastq
  -
    id: SRR000009
    label: sampleC
    condition: ongoing
    unit: rep3
    suffixes:
    - _1.fastq
    - _2.fastq
